# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CoolCalendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
end

target 'Custom UI' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'DateToolsSwift'
  pod 'CalendarKit'
end
